feat(ado/infra): introduce monorepo structure using lerna
microsoft/accessibility-insights-action pull request #752
Opened 2021-08-03 00:00 UTC by karanbirsingh

#### Details

This PR creates a monorepo structure in preparation for the Azure DevOps extension. I will update this description with more detailed info soon.

##### Motivation

##### Context

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Added relevant unit test for your changes. (`yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`yarn precheckin`)
- [ ] (after PR created) The `Accessibility Checks (pull_request)` check should fail. All other checks should pass.

2021-08-03 22:07 UTC, DaveTryon commented on packages/gh-action/dist/package.json
> +    "name": "accessibility-insights-gh-action",
Is the "-gh" needed here? We'll only publish 1 action

2021-08-03 23:03 UTC, DaveTryon commented on packages/gh-action/dist/package.json
> +    "name": "accessibility-insights-gh-action",
Thanks for explaining that this is just for the folder, and not reflected in any artifact

2021-08-04 16:00 UTC, DaveTryon approved these changes

2021-08-04 16:33 UTC, dbjorge commented on .vscode/settings.json
> +    "eslint.workingDirectories": ["packages/gh-action", "packages/shared"],
[The docs for the eslint extension](https://github.com/Microsoft/vscode-eslint#settings-options) suggest that `{ "pattern": "./packages/*/" }` should work and maybe be a little less prone to future breakage

2021-08-04 16:37 UTC, dbjorge commented on packages/shared/package.json
> +    "name": "shared",
I'd recommend against reusing the name of [an existing npm package](http://npmjs.com/package/shared); it's liable to cause confusing issues down the line. Consider instead using the repo name as a namespace (eg, `@accessibility-insights-action/shared`)

2021-08-04 16:43 UTC, dbjorge commented
It feels a little concerning that this increases the size of the bundled index.js by 39%; I wouldn't have expected it to change materially with this PR, so I'm suspicious there might be something missing here. Did you already investigate why the size increased so substantially? Are we bundling devDependencies accidentally?

2021-08-04 16:44 UTC, dbjorge requested changes
See inline

2021-08-04 22:55 UTC, karanbirsingh commented
> It feels a little concerning that this increases the size of the bundled index.js by 39%; I wouldn't have expected it to change materially with this PR, so I'm suspicious there might be something missing here. Did you already investigate why the size increased so substantially? Are we bundling devDependencies accidentally?

@dbjorge I think this is odd but expected behavior. Here's what I found using the vs-code diff view:

`index.js` gained about 3000 lines / 200,000 characters, almost all from the [npm encoding library](https://www.npmjs.com/package/encoding). The relevant snippet is below:

before:
```js
let convert;
try {
	convert = Object(function webpackMissingModule() { var e = new Error("Cannot find module 'encoding'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()).convert;
} catch (e) {}
```
after:
```js
let convert;
try {
	convert = __webpack_require__(/*! encoding */ "../../node_modules/encoding/lib/encoding.js").convert;
} catch (e) {}
```

This code [comes from an old version](https://github.com/node-fetch/node-fetch/blob/b5e2e41b2b50bf2997720d6125accaf0dd68c0ab/src/body.js#L14) of `node-fetch`. The [README at that tag](https://github.com/node-fetch/node-fetch/tree/v2.6.1#bodytextconverted) states: "(This API requires an optional dependency of the npm package encoding, which you need to install manually. webpack users may see a warning message due to this optional dependency.)"

Because `encoding` [wasn't specified in the dependencies](https://github.com/node-fetch/node-fetch/issues/412#issuecomment-379007792) of `node-fetch`, we never noticed this until now. In this PR, `encoding` is included **as a dev dependency of lerna**. webpack resolves the module and includes its source in `index.js`.

The other changes in the diff seem much smaller, so I think this is the primary cause of the change. I searched for some devDependencies like jest, and didn't see them in index.js.

2021-08-04 23:18 UTC, AhmedAbdoOrtiga approved these changes

2021-08-05 22:29 UTC, dbjorge commented
Discussed the encoding package thing with @karanbirsingh offline. He's going to look into avoiding bundling the new package (probably using `IgnorePlugin` like [this comment suggests](https://github.com/node-fetch/node-fetch/issues/412#issuecomment-379007792)). Clearing my review so it doesn't continue to block the PR after that's addressed.

2021-08-05 22:30 UTC, merged